name: Actualización Diaria Liturgia

on:
  schedule:
    - cron: '0 7 * * *'  # Todos los días a las 07:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4

      - name: Ejecutar scraper
        run: python scripts/get_liturgia.py

      - name: Mostrar JSON resultante
        run: cat liturgia.json

      - name: Git operaciones
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add liturgia.json
          git commit -m "Actualización diaria automática" || echo "Sin cambios, no se commit"
          git push origin main
