name: Actualizar Liturgia Diario

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Necesario para hacer git push
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario para hacer git push

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install requests beautifulsoup4

      - run: python scripts/get_liturgia.py

      - name: Commit and push changes
        run: |
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git pull --rebase origin main  # Primero actualiza el repositorio local
                git add liturgia.json
                git commit -m "Actualización automática diaria" || echo "No hay cambios para commitear"
                git push origin main
