name: Actualización Diaria Liturgia

on:
  schedule:
    - cron: '0 7 * * *'  # 7 AM UTC (8 AM en España)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Run scraper
        id: scraper
        run: python scripts/get_liturgia.py
        continue-on-error: true
      
      - name: Verify result
        run: |
          cat liturgia.json
          echo "URL utilizada: https://www.vaticannews.va/es/evangelio-de-hoy/$(date +'%Y/%m/%d').html"
      
      - name: Commit and push
        if: always()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add liturgia.json
          git commit -m "Actualización automática diaria" || exit 0
          git pull --rebase
          git push origin main
      
      - name: Create issue if failed
        if: steps.scraper.outcome == 'failure'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const data = fs.readFileSync('liturgia.json', 'utf8');
            const errorData = JSON.parse(data);
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Fallo en la actualización diaria - ${new Date().toLocaleDateString()}`,
              body: `Error al obtener la liturgia del día:\n\n\`\`\`json\n${JSON.stringify(errorData, null, 2)}\n\`\`\``,
              labels: ['automation-failed']
            });
